[package]
name = "minigrep"
version = "0.1.0"
authors = ["Kornel Domeradzki"]
edition = "2018"

[lib]
name = "minigrep_lib"
path = "src/lib.rs"


[[bin]]
name = "minigrep"
path = "src/main.rs"

[dependencies]
